#!/usr/bin/env ruby

require 'optparse'

EXECUTABLE_FILE = File.realpath(__FILE__)
$LOAD_PATH.unshift File.expand_path('../../lib', EXECUTABLE_FILE)

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = <<~EOS
    Usage: app
  EOS
  opts.on('-i', '--iterations ITER', Integer, 'Number of iterations') do |iter|
    options[:iter] = iter
  end

  opts.on('-d', '--use-ruby-solver', 'Debug mode: Use ruby solver') do
    ENV['SC_USE_RUBY_SOLVER'] = 'true'
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

option_parser.parse!

require 'seamless_cloning'

iterations = options[:iter] || 100_000

puts "Running #{iterations} iterations"
if ENV['SC_USE_RUBY_SOLVER']
  puts "Using ruby solver"
else
  puts "Using c-extension solver"
end

SeamlessCloning.clone(
  source: 'images/monster.png',
  target: 'images/wide_grass.png',
  mask_position: [50, 400],
  iterations: iterations
)
